
[workspace]

resolver = "2"
members = [
  "openapi-aide",
  "openapi-utoipa",
  "js-deno",
  "crud-sqlite-htmx",
  "crud-sqlite-openapi",
]

[workspace.lints.rust]
dead_code = "allow"
unused_variables = "allow"
